version: '3'

services:
  backend:
    env_file:
        "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "shop/backend"
    ports:
      - "5000:5000"
  frontend:
    env_file:
        "./frontend/.env"
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "shop/frontend"
    ports:
      - "3000:3000"
    links:
      - "backend"